#!/bin/bash
# Downloading genomes
datasets download genome accession --inputfile /mnt/d/BREX/BREXrep/BREXloc_project_2024/test_genome.txt --filename /mnt/d/BREX/BREXrep/BREXloc_project_2024/data/genomes.zip --include genome,gtf
unzip /mnt/d/BREX/BREXrep/BREXloc_project_2024/data/genomes.zip
