#!/bin/bash
#!/usr/bin/bash
#v1.1
# Загружает данные Генбанка по списку ID сборок
# Два аргумента. Первый - название файла со списком ID; второй - название папки, куда сохранятся результаты
# Переименовывает файлы 'genomic.gff' и 'protein.faa', добавляя к названию соответствующий ID сборки

datasets download genome accession --inputfile $1 --include genome,gff3,protein --filename $2.zip

echo "Download complete"

unzip -q $2.zip "ncbi_dataset/data/*" -d $2

rm $2.zip

echo "Files unpacked"

for NAME in $(ls $2/ncbi_dataset/data/ | grep "G")
do
mv $(ls $2/ncbi_dataset/data/${NAME}/*.gff) $2\/ncbi_dataset\/data\/${NAME}\/${NAME}_genomic.gff
done

for NAME in $(ls $2/ncbi_dataset/data/ | grep "G")
do
mv $(ls $2/ncbi_dataset/data/${NAME}/*.faa) $2\/ncbi_dataset\/data\/${NAME}\/${NAME}_protein.faa
done

echo "Files renamed"
