#!/bin/bash
# Downloading genomes
datasets download genome accession --inputfile ./BREXloc_project_2024/test_genome.txt --filename ./BREXloc_project_2024/data/genomes.zip --include genome,gtf
unzip ./BREXloc_project_2024/data/genomes.zip
