name: BREX_loci
channels:
  - padlocbio
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - aria2=1.37.0
  - binutils_impl_linux-64=2.40
  - biopython=1.83
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - cairo=1.18.0
  - curl=8.3.0
  - expat=2.6.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gawk=5.3.0
  - gcc_impl_linux-64=13.2.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gfortran_impl_linux-64=13.2.0
  - gmp=6.3.0
  - graphite2=1.3.13
  - grep=3.11
  - gxx_impl_linux-64=13.2.0
  - harfbuzz=8.3.0
  - hhsuite=3.3.0
  - hmmer=3.3.2
  - icu=73.2
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.21.2
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.3.0
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-devel_linux-64=13.2.0
  - libgcc-ng=13.2.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.1
  - libgomp=13.2.0
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libsanitizer=13.2.0
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libstdcxx-devel_linux-64=13.2.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.2.13
  - make=4.3
  - mmseqs2=15.6f452
  - mpfr=4.2.1
  - ncurses=6.5
  - numpy=1.26.4
  - openssl=3.3.0
  - padloc=2.0.0
  - pandoc=3.2
  - pango=1.50.14
  - pcre2=10.40
  - perl=5.32.1
  - pip=24.0
  - pixman=0.43.2
  - prodigal=2.6.3
  - pthread-stubs=0.4
  - python=3.10.14
  - python_abi=3.10
  - r-askpass=1.2.0
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.3.1
  - r-base64enc=0.1_3
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-blob=1.2.4
  - r-broom=1.0.6
  - r-bslib=0.7.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-cellranger=1.1.0
  - r-cli=3.6.2
  - r-clipr=0.8.0
  - r-colorspace=2.1_0
  - r-conflicted=1.2.0
  - r-cpp11=0.4.7
  - r-crayon=1.5.2
  - r-curl=5.1.0
  - r-data.table=1.15.2
  - r-dbi=1.2.2
  - r-dbplyr=2.5.0
  - r-digest=0.6.35
  - r-dplyr=1.1.4
  - r-dtplyr=1.3.1
  - r-ellipsis=0.3.2
  - r-evaluate=0.23
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.2
  - r-forcats=1.0.0
  - r-fs=1.6.4
  - r-gargle=1.5.2
  - r-generics=0.1.3
  - r-getopt=1.20.3
  - r-ggplot2=3.5.1
  - r-glue=1.7.0
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gtable=0.3.5
  - r-haven=2.5.4
  - r-highr=0.10
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-httr=1.4.7
  - r-ids=1.0.1
  - r-isoband=0.2.7
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.8
  - r-knitr=1.46
  - r-labeling=0.4.3
  - r-lattice=0.22_6
  - r-lifecycle=1.0.4
  - r-lubridate=1.9.3
  - r-magrittr=2.0.3
  - r-mass=7.3_60
  - r-matrix=1.6_5
  - r-memoise=2.0.1
  - r-mgcv=1.9_1
  - r-mime=0.12
  - r-modelr=0.1.11
  - r-munsell=0.5.1
  - r-nlme=3.1_164
  - r-openssl=2.2.0
  - r-pillar=1.9.0
  - r-pkgconfig=2.0.3
  - r-prettyunits=1.2.0
  - r-processx=3.8.4
  - r-progress=1.2.3
  - r-ps=1.7.6
  - r-purrr=1.0.2
  - r-r6=2.5.1
  - r-ragg=1.3.2
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-readr=2.1.5
  - r-readxl=1.4.3
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-reprex=2.1.0
  - r-rlang=1.1.3
  - r-rmarkdown=2.27
  - r-rstudioapi=0.16.0
  - r-rvest=1.0.4
  - r-sass=0.4.9
  - r-scales=1.3.0
  - r-selectr=0.4_2
  - r-stringi=1.8.4
  - r-stringr=1.5.1
  - r-sys=3.4.2
  - r-systemfonts=1.1.0
  - r-textshaping=0.3.7
  - r-tibble=3.2.1
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-tinytex=0.51
  - r-tzdb=0.4.0
  - r-utf8=1.2.4
  - r-uuid=1.2_0
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-withr=3.0.0
  - r-xfun=0.44
  - r-xml2=1.3.6
  - r-yaml=2.3.7
  - readline=8.2
  - sed=4.8
  - setuptools=70.0.0
  - sysroot_linux-64=2.12
  - tk=8.6.13
  - tktable=2.10
  - tzdata=2024a
  - wget=1.21.4
  - wheel=0.43.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - certifi==2024.2.2
      - frozenlist==1.4.1
      - idna==3.7
      - lxml==5.2.2
      - markupsafe==2.1.5
      - multidict==6.0.5
      - pandas==2.2.2
      - pillow==10.3.0
      - pytz==2024.1
      - six==1.16.0
      - urllib3==2.2.1
      - yarl==1.9.4
